branches:
  only:
  - master-doc-es
language: python
cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
python:
- 2.7
install:
- pip install -r doc/requirements.txt
- pip install -r requirements.txt
script:
- cd doc
- make deploy -s
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    - GH_REF: github.com/vauxoo/odoo.git
    - GH_BRANCH: gh-pages
    - GH_COMMITER_EMAIL: cowardvasallwrite@vauxoo.com
    - GH_COMMITER_NAME: "Travis Robot."
    - secure: "BsND9egB6crZ6Gm3FLiP2YTfJ8K1+H7QYJMpwt3eBtHCDepwyhypxL9tS4RkAdglucVweKMoniUfRZsZryoNXkQ8ntNhyoPkfPLTjrqvcCAdyGMj/6WnP5vuZrNQ0dC9djB2F/TdPxuzPiqZjpLHuCQ7Rp0JYLrJzVFlPU8fCnY="

